FROM rust:1.68

WORKDIR /app

RUN dpkg --add-architecture arm64 && apt-get update && apt-get install -y --no-install-recommends \
    gcc-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add aarch64-unknown-linux-gnu

RUN uname -a > arch.txt && rustup show >> arch.txt

COPY . .

# RUN cargo build --verbose --release
RUN PKG_CONFIG_SYSROOT_DIR=/ \
    cargo build --release --target aarch64-unknown-linux-gnu